# Generated by Django 4.2.1 on 2023-05-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_funko_number_funko_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='funko',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
