# Generated by Django 4.2.1 on 2023-05-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='collection',
            field=models.ManyToManyField(blank=True, related_name='collection_profiles', to='main_app.funko'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='funko',
            field=models.ManyToManyField(blank=True, related_name='funko_profiles', to='main_app.funko'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlist_profiles', to='main_app.funko'),
        ),
    ]
