# Generated by Django 4.2.1 on 2023-05-16 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_profile_collection_alter_profile_funko_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='funko',
        ),
    ]
